FROM maven:3.8.3-openjdk-17-slim AS build
WORKDIR /project
COPY api/vtb-stat/pom.xml .
RUN mvn dependency:go-offline
COPY api/vtb-stat/src/ /project/src
RUN mvn package

FROM openjdk:17-alpine AS runtime
RUN mkdir /app
RUN addgroup -g 1001 -S alekseigroup
RUN adduser -S aleksei -u 1001
COPY --from=build /project/target/vtb-stat-1.0.jar /app/vtb-stat.jar
WORKDIR /app
RUN chown -R aleksei:alekseigroup /app
EXPOSE 8080
CMD java $JAVA_OPTS -jar vtb-stat.jar
